# Generated by Django 5.0.8 on 2025-10-06 05:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockedScheduleProxy',
            fields=[
            ],
            options={
                'verbose_name': 'زمان\u200cبندی یکباره',
                'verbose_name_plural': 'زمان\u200cبندی\u200cهای یکباره',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.clockedschedule',),
        ),
        migrations.CreateModel(
            name='CrontabScheduleProxy',
            fields=[
            ],
            options={
                'verbose_name': 'زمان\u200cبندی Crontab',
                'verbose_name_plural': 'زمان\u200cبندی\u200cهای Crontab',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.crontabschedule',),
        ),
        migrations.CreateModel(
            name='IntervalScheduleProxy',
            fields=[
            ],
            options={
                'verbose_name': 'زمان\u200cبندی بازه\u200cای',
                'verbose_name_plural': 'زمان\u200cبندی\u200cهای بازه\u200cای',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.intervalschedule',),
        ),
        migrations.CreateModel(
            name='PeriodicTaskProxy',
            fields=[
            ],
            options={
                'verbose_name': 'وظیفه تناوبی',
                'verbose_name_plural': 'وظایف تناوبی',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رویداد ورود',
                'verbose_name_plural': 'رویدادهای ورود',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('activities_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جلسه کاری',
                'verbose_name_plural': 'جلسات کاری',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'ورود'), ('logout', 'خروج'), ('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('view', 'مشاهده')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ فعالیت کاربر',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت کاربران',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='accounts_us_user_id_5cc93e_idx'), models.Index(fields=['action', 'timestamp'], name='accounts_us_action_fb1cb3_idx')],
            },
        ),
    ]
