# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_activity_tracking'),
        ('accounts', '0001_initial'),
    ]

    operations = [
    ]