# Generated by Django 5.0.8 on 2025-10-06 05:38

import django.db.models.deletion
import django.utils.timezone
import pgvector.django
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('embeddings', '0001_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique identifier for the model (e.g., intfloat/multilingual-e5-base)', max_length=200, unique=True, verbose_name='نام مدل')),
                ('display_name', models.CharField(help_text='Human-readable name for the model', max_length=200, verbose_name='نام نمایشی')),
                ('dimension', models.PositiveIntegerField(help_text='Vector dimension for this model', verbose_name='بعد بردار')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is currently active for generating embeddings', verbose_name='فعال')),
                ('model_path', models.CharField(blank=True, help_text='Path or identifier for loading the model', max_length=500, verbose_name='مسیر مدل')),
                ('description', models.TextField(blank=True, help_text='Description of the model and its use cases', verbose_name='توضیحات')),
                ('avg_processing_time', models.FloatField(blank=True, help_text='Average processing time per text in seconds', null=True, verbose_name='زمان پردازش متوسط (ثانیه)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Model-specific configuration parameters', verbose_name='تنظیمات')),
            ],
            options={
                'verbose_name': 'مدل امبدینگ',
                'verbose_name_plural': 'مدل\u200cهای امبدینگ',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmbedding',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('object_id', models.UUIDField()),
                ('model_name', models.CharField(default='distiluse-base-multilingual-cased-v2', help_text='Legacy model name field', max_length=100, verbose_name='نام مدل')),
                ('model_id', models.CharField(db_index=True, help_text='Unique identifier for the embedding model (e.g., hakim-v1, sbert-MatinaSRoberta)', max_length=200, verbose_name='شناسه مدل')),
                ('model_version', models.CharField(blank=True, help_text='Version string for the embedding model', max_length=50, null=True, verbose_name='نسخه مدل')),
                ('vector', pgvector.django.VectorField(dimensions=1024, verbose_name='بردار')),
                ('dimension', models.PositiveIntegerField(default=1024, verbose_name='بعد بردار (legacy)')),
                ('dim', models.PositiveIntegerField(db_index=True, help_text='Dimension of the embedding vector', verbose_name='بعد بردار')),
                ('text_content', models.TextField(verbose_name='محتوای متنی')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical جاسازی',
                'verbose_name_plural': 'historical جاسازی\u200cها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('model_name', models.CharField(default='distiluse-base-multilingual-cased-v2', help_text='Legacy model name field', max_length=100, verbose_name='نام مدل')),
                ('model_id', models.CharField(db_index=True, help_text='Unique identifier for the embedding model (e.g., hakim-v1, sbert-MatinaSRoberta)', max_length=200, verbose_name='شناسه مدل')),
                ('model_version', models.CharField(blank=True, help_text='Version string for the embedding model', max_length=50, null=True, verbose_name='نسخه مدل')),
                ('vector', pgvector.django.VectorField(dimensions=1024, verbose_name='بردار')),
                ('dimension', models.PositiveIntegerField(default=1024, verbose_name='بعد بردار (legacy)')),
                ('dim', models.PositiveIntegerField(db_index=True, help_text='Dimension of the embedding vector', verbose_name='بعد بردار')),
                ('text_content', models.TextField(verbose_name='محتوای متنی')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'جاسازی',
                'verbose_name_plural': 'جاسازی\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='embeddings__content_6bab1d_idx'), models.Index(fields=['model_name'], name='embeddings__model_n_129096_idx'), models.Index(fields=['dimension'], name='embeddings__dimensi_7c328f_idx'), models.Index(fields=['model_id'], name='embeddings__model_i_216ec4_idx'), models.Index(fields=['dim'], name='embeddings__dim_91bcd9_idx'), models.Index(fields=['content_type', 'object_id', 'model_id'], name='embeddings_content_model_idx'), models.Index(fields=['model_id', 'dim'], name='embeddings_model_dim_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='embedding',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'model_id'), name='unique_embedding_per_content_model'),
        ),
    ]
