# Generated by Django 5.0.8 on 2025-11-22 08:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0009_simplify_synclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_id', models.UUIDField(db_index=True, help_text='ID چانکی که حذف شده', verbose_name='Chunk ID (حذف شده)')),
                ('embedding_id', models.UUIDField(db_index=True, help_text='ID embedding که حذف شده', verbose_name='Embedding ID (حذف شده)')),
                ('node_id', models.UUIDField(blank=True, db_index=True, help_text='ID نود در Core/Qdrant که باید حذف شود', null=True, verbose_name='Node ID در Core')),
                ('deletion_status', models.CharField(choices=[('pending', 'در انتظار حذف از Core'), ('success', 'حذف موفق از Core'), ('failed', 'خطا در حذف از Core'), ('local_only', 'فقط از Ingest حذف شد (به Core sync نشده بود)')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت حذف')),
                ('deleted_from_ingest_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان حذف از Ingest')),
                ('deleted_from_core_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حذف از Core')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش مجدد')),
                ('last_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تلاش')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('chunk_metadata', models.JSONField(blank=True, help_text='اطلاعات chunk برای reference', null=True, verbose_name='اطلاعات Chunk')),
            ],
            options={
                'verbose_name': 'لاگ حذف',
                'verbose_name_plural': 'لاگ\u200cهای حذف',
                'ordering': ['-deleted_from_ingest_at'],
                'indexes': [models.Index(fields=['deletion_status', 'retry_count'], name='embeddings__deletio_4c54cd_idx'), models.Index(fields=['node_id', 'deletion_status'], name='embeddings__node_id_3690d6_idx'), models.Index(fields=['deleted_from_ingest_at'], name='embeddings__deleted_309f7f_idx')],
            },
        ),
    ]
