# Generated by Django 5.0.8 on 2025-10-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrumentwork',
            unique_together=set(),
        ),
    ]
