# Generated by Django 5.0.8 on 2025-11-23 14:19

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_chunk_options_alter_historicalchunk_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LUnit',
            fields=[
            ],
            options={
                'verbose_name': 'بند سند حقوقی',
                'verbose_name_plural': 'بندهای اسناد حقوقی',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.legalunit',),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='historicalqaentry',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical پرسش و پاسخ', 'verbose_name_plural': 'historical پرسش و پاسخ'},
        ),
        migrations.AlterModelOptions(
            name='qaentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرسش و پاسخ', 'verbose_name_plural': 'پرسش و پاسخ'},
        ),
        migrations.AlterField(
            model_name='historicallegalunit',
            name='unit_type',
            field=models.CharField(choices=[('part', 'باب'), ('chapter', 'فصل'), ('section', 'قسمت'), ('article', 'ماده'), ('clause', 'بند'), ('subclause', 'زیربند'), ('note', 'تبصره'), ('appendix', 'ضمیمه')], max_length=20, verbose_name='نوع واحد'),
        ),
        migrations.AlterField(
            model_name='legalunit',
            name='unit_type',
            field=models.CharField(choices=[('part', 'باب'), ('chapter', 'فصل'), ('section', 'قسمت'), ('article', 'ماده'), ('clause', 'بند'), ('subclause', 'زیربند'), ('note', 'تبصره'), ('appendix', 'ضمیمه')], max_length=20, verbose_name='نوع واحد'),
        ),
    ]
