# Generated by Django 5.0.8 on 2025-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_remove_order_index_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalunit',
            name='order_index',
            field=models.PositiveIntegerField(help_text='ترتیب نمایش (اجباری)', verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='historicallegalunit',
            name='order_index',
            field=models.PositiveIntegerField(help_text='ترتیب نمایش (اجباری)', verbose_name='ترتیب'),
        ),
    ]
