# Generated by Django 5.0.8 on 2025-12-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_change_order_index_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallegalunit',
            name='order_index',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='legalunit',
            name='order_index',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ترتیب'),
        ),
    ]
