# Generated by Django 5.0.8 on 2025-12-14 11:34

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_change_order_index_to_charfield'),
        ('masterdata', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTextEntry',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=500, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, help_text='متن را مستقیم وارد کنید یا فایل آپلود کنید', verbose_name='محتوا')),
                ('source_file', models.TextField(blank=True, help_text='فرمت\u200cهای مجاز: md, txt, xml, html, htm, doc, docx', max_length=100, null=True, verbose_name='فایل منبع')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='نام فایل اصلی')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical متن',
                'verbose_name_plural': 'historical متون',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, help_text='متن را مستقیم وارد کنید یا فایل آپلود کنید', verbose_name='محتوا')),
                ('source_file', models.FileField(blank=True, help_text='فرمت\u200cهای مجاز: md, txt, xml, html, htm, doc, docx', null=True, upload_to='text_entries/%Y/%m/', verbose_name='فایل منبع')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='نام فایل اصلی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_text_entries', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('related_units', models.ManyToManyField(blank=True, related_name='related_text_entries', to='documents.legalunit', verbose_name='بندهای مرتبط')),
            ],
            options={
                'verbose_name': 'متن',
                'verbose_name_plural': 'متون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextEntryVocabularyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='وزن برچسب (1.0 = عادی)', verbose_name='وزن')),
                ('text_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.textentry', verbose_name='متن')),
                ('vocabulary_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.vocabularyterm', verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'برچسب متن',
                'verbose_name_plural': 'برچسب\u200cهای متن',
                'unique_together': {('text_entry', 'vocabulary_term')},
            },
        ),
        migrations.AddField(
            model_name='textentry',
            name='vocabulary_terms',
            field=models.ManyToManyField(blank=True, related_name='text_entries', through='documents.TextEntryVocabularyTerm', to='masterdata.vocabularyterm', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddIndex(
            model_name='textentry',
            index=models.Index(fields=['title'], name='documents_t_title_0869cd_idx'),
        ),
        migrations.AddIndex(
            model_name='textentry',
            index=models.Index(fields=['created_at'], name='documents_t_created_b44d33_idx'),
        ),
    ]
