# Generated by Django 5.0.8 on 2025-12-14 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_add_textentry_model'),
        ('masterdata', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qaentry',
            name='documents_q_status_74d214_idx',
        ),
        migrations.RemoveIndex(
            model_name='qaentry',
            name='documents_q_approve_a3bdb1_idx',
        ),
        migrations.RemoveField(
            model_name='historicalqaentry',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicalqaentry',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalqaentry',
            name='source_unit',
        ),
        migrations.RemoveField(
            model_name='historicalqaentry',
            name='source_work',
        ),
        migrations.RemoveField(
            model_name='historicalqaentry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='qaentry',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='qaentry',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='qaentry',
            name='source_unit',
        ),
        migrations.RemoveField(
            model_name='qaentry',
            name='source_work',
        ),
        migrations.RemoveField(
            model_name='qaentry',
            name='status',
        ),
        migrations.AddField(
            model_name='qaentry',
            name='related_units',
            field=models.ManyToManyField(blank=True, related_name='related_qa_entries', to='documents.legalunit', verbose_name='بندهای مرتبط'),
        ),
        migrations.AddIndex(
            model_name='qaentry',
            index=models.Index(fields=['created_at'], name='documents_q_created_60985c_idx'),
        ),
    ]
