# Generated by Django 5.0.8 on 2025-12-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_add_through_models_for_autocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='textentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.textentry', verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='historicalchunk',
            name='textentry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.textentry', verbose_name='متن'),
        ),
    ]
